name: ouster-ros

on:
  push:
    branches:
      - ros2-foxy
  pull_request:
    branches:
      - ros2-foxy

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distro:
          - foxy
          - galactic
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build the Docker image
        run: |
          docker build .                                    \
            --build-arg ROS_DISTRO=${{ matrix.ros_distro }} \
            --file Dockerfile                               \
            --tag ouster-ros-${{ matrix.ros_distro }}:$(date +%s)
